sudo: false
cache: pip
language: python
python:
- 3.6
matrix:
  include:
    - env: TOXENV=py
    - env: TOXENV=manifest
    - env: TOXENV=readme
    - env: TOXENV=flake8

install:
- pip install --upgrade pip
- pip install tox
- pip install codecov
- pip install coverage
script:
- tox
after_success:
- tox -e coverage-report
- codecov
